package rules;

import com.vincent.entity.Order;

// 100元以下，不加分
rule "score_1"
when
    $order:Order(amount < 100);
then
    $order.setScore(0);
    System.out.println("100元以下，不加分");
end

// 100-500 加100分
rule "score_2"
when
    $order:Order(amount > 100 && amount < 500);
then
    $order.setScore(100);
    System.out.println("100-500 加100分");
end

// 500-1000 加500分
rule "score_3"
when
    $order:Order(amount>500&&amount<1000);
then
    $order.setScore(500);
    System.out.println("500-1000 加500分");
end

// 1000以上 加1000分
rule "score_4"
when
    $order:Order(amount>=1000);
then
    $order.setScore(1000);
    System.out.println("1000以上 加1000分");
end